### ISSUE TITLE
ImportError: DLL load failed while importing cameras: The specified module could not be found.

### ISSUE THREAD

**Issue by Raduq91** [bensondaled/pseyepy#13]
```


(venv) C:\Users\Radu\Downloads\Portable Python-3.10.5 x64>qw.py
Traceback (most recent call last):
  File "C:\Users\Radu\Downloads\Portable Python-3.10.5 x64\qw.py", line 1, in <module>
    from pseyepy import Cameras
  File "C:\Users\Radu\Downloads\Portable Python-3.10.5 x64\venv\lib\site-packages\pseyepy\__init__.py", line 1, in <module>
    from .cameras import Camera, cam_count
ImportError: DLL load failed while importing cameras: The specified module could not be found.
```

**Comment by DawidStankiewicz** [comment]
@Raduq91 did you solve this issue? I have the same problem.

**Comment by Raduq91** [comment]
> @Raduq91 did you solve this issue? I have the same problem.

I used https://github.com/jkevin/PS3EyeDirectShow

**Comment by lucid-codr** [comment]
> > @Raduq91 did you solve this issue? I have the same problem.
> 
> I used https://github.com/jkevin/PS3EyeDirectShow

can you use it in python with 120 fps ?

**Comment by Raduq91** [comment]
> > > @Raduq91 did you solve this issue? I have the same problem.
> > 
> > 
> > I used https://github.com/jkevin/PS3EyeDirectShow
> 
> can you use it in python with 120 fps ?

I did some modifications(I am beginner in programing) to "PS3EyePushPin.cpp"  and for me it seems it worked, I remember I could specify what fps I want and it worked.
![image](https://github.com/user-attachments/assets/147bc221-5870-492a-a7d6-cd5a815a8c61)

`camera = cv2.VideoCapture(0)
camera.set(5,120)
camera.set(cv2.CAP_PROP_FRAME_WIDTH, 320)
camera.set(cv2.CAP_PROP_FRAME_HEIGHT, 240)`
