### ISSUE TITLE
Why I got the error message"ImportError: No module named cameras"

### ISSUE THREAD

**Issue by autocomputer** [bensondaled/pseyepy#16]
Hi, I compiled the code successfully and when I run pip list, the followings were shown.
pseyepy 0.0
But when I run Python3 in interactive mode and input "from pseyepy import Camera", the following error occured. Could you tell me why this happened? Thanks.
>>> from pseyepy import Camera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pseyepy/__init__.py", line 1, in <module>
    from .cameras import Camera, cam_count
ImportError: No module named cameras

**Comment by autocomputer** [comment]
Hi, I've solved the problem by reading https://github.com/bensondaled/pseyepy/issues/5. Run python3 out of pseyepy-master and everything is OK.
